# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:59
from __future__ import unicode_literals

from django.db import migrations
import django_markup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160223_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markup',
            field=django_markup.fields.MarkupField(choices=[('none', 'None (no processing)'), ('linebreaks', 'Linebreaks'), ('markdown', 'Markdown'), ('restructuredtext', 'reStructuredText')], default='markdown', max_length=255, verbose_name='markup'),
        ),
    ]
