# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 2, 23, 21, 46, 2, 704759, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
