# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_desc',
            field=models.CharField(default=datetime.datetime(2016, 2, 23, 21, 58, 6, 346837, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
    ]
